server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Ponemos false para evitar conflictos con rutas automáticas
          lower-case-service-id: true
      routes:
        - id: reservas-route
          uri: lb://reservas-service     # <--- CORREGIDO: Coincide con spring.application.name
          predicates:
            - Path=/reservas/**
          filters:
            - StripPrefix=1              # <--- LA SOLUCIÓN: Elimina "/reservas" antes de enviar

        - id: usuarios-route
          uri: lb://usuario-service              # Verifica si tu servicio se llama "usuario" o "usuario-service"
          predicates:
            - Path=/usuario/**
          filters:
            - StripPrefix=1              # <--- Agregado también aquí por seguridad

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/